SHELL_DATA_DIR="$SHELL_DIR/data"

SHELL_CACHE_DIR="$SHELL_DATA_DIR/cache"
SHELL_STARTUP_FILE="$SHELL_CACHE_DIR/startup.zsh"

SHELL_PLUGINS_DIR="$SHELL_DATA_DIR/plugins"

SHELL_STARTUP_DIR="$SHELL_DIR/startup"
SHELL_STARTUP_FILES_DIR="$SHELL_STARTUP_DIR/files"

SHELL_INSTALL_DIR="$SHELL_DIR/install"
SHELL_INSTALL_FILES_DIR="$SHELL_INSTALL_DIR/files"

SHELL_EVENTS_DIR="$SHELL_DIR/events"

SHELL_SCRIPTS_DIR="$SHELL_DIR/scripts"

SHELL_LINKS_DIR="$SHELL_DIR/links"