export SHELL_PREFFIX="shell "

export SHELL_PREFFIX_ECHO="${COLOR_CYAN}$SHELL_PREFFIX${STYLE_RESET} 💬"
export SHELL_PREFFIX_ERROR="${COLOR_ERROR}$SHELL_PREFFIX${STYLE_RESET} ❌"
export SHELL_PREFFIX_SUCCESS="${COLOR_SUCCESS}$SHELL_PREFFIX${STYLE_RESET} ✅"
export SHELL_PREFFIX_INFO="${COLOR_CYAN}$SHELL_PREFFIX${STYLE_RESET} ℹ️"
export SHELL_PREFFIX_DEBUG="${COLOR_DEBUG}$SHELL_PREFFIX${STYLE_RESET} 🚧"
