source "$AZ_DIR/system/define/env.zsh"
source "$AZ_DIR/system/define/paths.zsh"
source "$AZ_DIR/system/define/trace.zsh"
source "$AZ_DIR/system/define/guard.zsh"
source "$AZ_DIR/system/define/source.zsh"
