SHELL_CACHE_DIR="$SHELL_DIR/cache"
SHELL_PLUGINS_DIR="$SHELL_CACHE_DIR/plugins"
SHELL_STARTUP_FILE="$SHELL_CACHE_DIR/startup.zsh"
SHELL_SETUP_COMPLETE_FILE="$SHELL_CACHE_DIR/setup-complete.zsh"
SHELL_DOWNLOAD_DIR="$SHELL_CACHE_DIR/download"

SHELL_INSTALL_DIR="$SHELL_DIR/install"
SHELL_INSTALL_FILES_DIR="$SHELL_INSTALL_DIR/files"

SHELL_EVENTS_DIR="$SHELL_DIR/events"

SHELL_SCRIPTS_DIR="$SHELL_DIR/scripts"